### ISSUE TITLE
not founding peers 

### ISSUE THREAD

**Issue by sivanagarajumolabant** [8468/bitboot#2]
if i ran the example.js file in my system it is not finding any peers
and moreover iam new to this technology 

after ran the example.js file it was giving some log messages here:

bitboot function
Using rally point bitboot (f659ba883e49be3891deccd12b7c7bf96343bcad)
bootstrap function
Joining network with id f65902e716dca34fe8ed55b7a708225b7b5cbcad (distance to rally 1.6066485897541828e+43)
I have a new node id: f65902e716dca34fe8ed55b7a708225b7b5cbcad
onready function
search function
Searching for nodes near rally point
finished function
I found peers: []
Waddling closer to the rally point destroying old DHT connection
restart function
Joining network with id f659b2e716dca34fe8ed55b7a708225b7b5cbcad (distance to rally 7.34723573552025e+41)
I have a new node id: f659b2e716dca34fe8ed55b7a708225b7b5cbcad
onready function
sayhi function
search function
Searching for nodes near rally point
finished function
I found peers: []
search function
Searching for nodes near rally point
finished function
I found peers: []
search function
Searching for nodes near rally point
finished function
I found peers: []
search function
Searching for nodes near rally point
finished function
I found peers: []
search function
Searching for nodes near rally point
finished function
I found peers: []

**Comment by bmuller** [comment]
@sivanagarajumolabant - can you please provide:
1. A copy of the code you're running
2. A description of the 2 machines you're running this code on (version of node, version of bitboot, OS, OS version, etc)
3. A description of your network (are the 2 machines on the same LAN, are they on internet visible IP's, etc).

**Comment by sivanagarajumolabant** [comment]
node js version -->  10
os----> windows 10
what ever the code you written that files only iam using 
i run the example.js code and index.js files
no, 2  machines are run on thedifferent LAN with DHCP network

**Comment by bmuller** [comment]
@sivanagarajumolabant I'm going to need answers to all my questions to be most helpful.  Please provide all answers, as well as the IP address shown at https://www.whatismypublicip.com as viewed on each computer (or, at least, is the IP address the same on both computers).

**Comment by sivanagarajumolabant** [comment]
iam using windows 10 for one machine and second one is for VM ware (windows 7 OS)

the two machines are running in same LAN network and both having same IP address
Your Public IP Address Is:
183.82.98.101

**Comment by bmuller** [comment]
As far as the DHT is concerned, there's only one node at 183.82.98.101.  You can't find yourself using bitboot any more than you can call yourself on your own phone number.

**Comment by sivanagarajumolabant** [comment]
Iam calling bitboot magic name on the both machines how can I resolve and
how to find the peers can please explain me today I will try , if I have
any doubts  I will let you know

**Comment by bmuller** [comment]
@sivanagarajumolabant The network sees both machines as a single machine since the IP address is the same on both.  You can't call your own phone number, you can't send a fax from one machine to itself, and you can't use bitboot to look for your own node.

I'm locking this issue to prevent any more distraction.
